services:

  mongodb:
    image: mongo:7
    container_name: radar-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - radar-network

  redis:
    image: redis/redis-stack:latest
    container_name: radar-redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    networks:
      - radar-network

  fake-generator:
    build: .
    container_name: radar-fake-generator
    command: python -m src.generator.fake_generator
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - mongodb
    restart: "no"
    networks:
      - radar-network

  pipeline:
    build: .
    container_name: radar-pipeline
    command: sh -c "sleep 20 && python -m src.pipeline.mongo_to_redis"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - mongodb
      - redis
      - fake-generator
    restart: always
    networks:
      - radar-network

  dashboard:
    build: .
    container_name: radar-dashboard
    command: streamlit run src/app/app.py --server.port=8501 --server.address=0.0.0.0
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8502:8501"
    depends_on:
      - mongodb
      - redis
      - pipeline
    restart: always
    networks:
      - radar-network

volumes:
  mongodb_data:
  redis_data:

networks:
  radar-network:
    driver: bridge